config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  resources :users, only: [:index, :show]
  resources :contacts do
    resources :events, shallow: true
  end
  get '/events', to: 'events#overview'

  devise_for :users, path: 'member'
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
  end
end

app/views/shared/_flash_messages.html.erb
<div class="message is-<%= type %>">
    <div class="message-body">
        <%= msg %>
        <button class="delete" aria-label="delete"></button>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>Personal CRM</strong> by <a href="#">Colton Juliano</a>.
    </p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a href=<%=root_path%> class="navbar-item">
      <figure>📇</figure>
    </a>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasic">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasic" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", root_path, class: "navbar-item"%>
      <%= link_to 'Contacts', contacts_path, class: "navbar-item" %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
            <%= link_to 'Account', user_path(current_user), class: "navbar-item button" %>
            <%= link_to "Sign out", destroy_user_session_path, method: 'delete', class: "navbar-item button is-warning is-light" %>
        </div>
      </div>
    </div>
  </div>
</nav>