config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  resources :users, only: [:index, :show]
  resources :contacts do
    resources :events, shallow: true
  end
  get '/events', to: 'events#overview'

  devise_for :users, path: 'member'
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
  end
end

app/models/event.rb
class Event < ApplicationRecord
    validates :date, presence: true
    validates :interaction_type, inclusion: {in: %w(call text message videochat email mail solo_encounter group_encounter)}
    
    belongs_to :contact
    belongs_to :user

    delegate :contact_image, :first_name, :display_contact_image, to: :contact

    scope :recent_events, -> {where('date < ?', Date.today).order('date DESC').limit(6)}
    scope :upcoming_events, -> {where('date >= ?', Date.today).order(:date).limit(6)}
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :require_event_ownership, only: [:show, :edit, :update, :destroy]
    before_action :require_contact_ownership, only: [:new, :create]

    def index
        @contact = Contact.find(params[:contact_id])
        @events = @contact.events.order(date: :desc)
    end

    def new
        @event = Contact.find(params[:contact_id]).events.new
    end

    def create
        @contact = Contact.find(params[:contact_id])
        @event = @contact.events.new(event_params)
        @event.user_id = current_user.id
        if @event.save
            # redirect_to contact_events_url(@contact) when the "all events" calendar has more functionality/js
            redirect_to @contact
        else
            flash[:error] = @event.errors.full_messages
            redirect_back(fallback_location: @contact)
        end
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update
        @event = Event.find(params[:id])
        if @event.update(edit_event_params)
            flash[:success] = "event updated!"
            redirect_to contact_path(@event.contact)
        else
            flash.now[:error] = @event.errors.full_messages
            render :edit
        end
    end

    def destroy
        @event = Event.find(params[:id])
        if @event.destroy
            flash[:success] = "Event canceled"
            redirect_to root_url
        else
            flash[:error] = @event.errors.full_messages
            redirect_to root_url
        end
    end

    def overview
        @events = current_user.events
    end

    private

        def event_params
            params.require(:events).permit(:interaction_type, :description, :date)
        end

        def edit_event_params
            params.require(:event).permit(:interaction_type, :description, :date)
        end

        def require_event_ownership
            event = Event.find(params[:id])
            unless event.user_id == current_user.id
                response = {error: "You don't own that event"}
                render json: response, status: 401
            end
        end

        def require_contact_ownership
            contact = Contact.find(params[:contact_id])
            unless contact.user_id == current_user.id
                response = {error: "You don't own that contact"}
                render json: response, status: 401
            end
        end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_form.html.erb
<div class="columns">
    <div class="column is-one-quarter">
        <%= form_with model: contact, :url => contact_events_path, :method => :post do |f| %>
            <%= f.simple_fields_for :events do |r| %>
                <%= r.input :interaction_type do %>
                    <div class="control">
                        <div class="select">
                            <%= r.select :interaction_type, ["call", "text", "message", "videochat", "email", "mail", "solo_encounter", "group_encounter"] %>
                        </div>
                    </div>
                <% end %>

                <%= r.input :description, as: :text %>
                <%= r.input :date, as: :date, html5: true %>
                <%= r.submit 'Save Event', class: "button is-primary" %>
                <%= link_to "Cancel", :back, class: "button is-light" %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/events/edit.html.erb
<h1 class="title is-1">Edit Event</h1>

            <%= simple_form_for @event do |r| %>
                <%= r.input :interaction_type do %>
                    <div class="control">
                        <div class="select">
                            <%= r.select :interaction_type, ["call", "text", "message", "videochat", "email", "mail", "solo_encounter", "group_encounter"] %>
                        </div>
                    </div>
                <% end %>

                <%= r.input :description, as: :text %>
                <%= r.input :date, as: :date, html5: true %>
                <%= r.submit 'Save Event', class: "button is-primary" %>
                <%= link_to "Cancel", :back, class: "button is-light" %>
            <% end %>

app/views/events/index.html.erb
ALL EVENTS
<br>
<% @events.each do |e| %>
    <%= e.interaction_type %> <%= e.date %>
    <br>
<% end %>

app/views/events/new.html.erb
<h1 class="title is-1">New Event With <%= @event.contact.first_name %></h1>

<%= form_with model: @contact, :url => contact_events_path, :method => :post do |f| %>
    <%= f.simple_fields_for :events do |r| %>
        <%= r.input :interaction_type do %>
            <div class="control">
                <div class="select">
                    <%= r.select :interaction_type, ["call", "text", "message", "videochat", "email", "mail", "solo_encounter", "group_encounter"] %>
                </div>
            </div>
        <% end %>

        <%= r.input :description, as: :text %>
        <%= r.input :date, as: :date, html5: true %>
        <%= r.submit 'Save Event', class: "button is-primary" %>
        <%= link_to "Cancel", :back, class: "button is-light" %>
    <% end %>
<% end %>

app/views/events/overview.html.erb
<%= month_calendar(attribute: :date, events: @events) do |date, events| %>
    <%= date.day %>

    <% events.each do |event| %>
        <div>
            <%= event.interaction_type %> with <%= link_to event.contact.first_name %>
            <%#= event.contact %>
        </div>
    <% end %>
<% end %>