config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  resources :users, only: [:index, :show]
  resources :contacts do
    resources :events, shallow: true
  end
  get '/events', to: 'events#overview'

  devise_for :users, path: 'member'
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_up', to: 'devise/registrations#new'
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :user
    has_many :events, dependent: :destroy

    validates :first_name, presence: true
    has_one_attached :contact_image

    accepts_nested_attributes_for :events, allow_destroy: true

    before_validation :set_nils

    def full_name
        if self.nickname
            "#{self.first_name || ''} #{self.last_name || ''} (#{self.nickname})"
        else
            "#{self.first_name || ''} #{self.last_name || ''}"
        end
    end
    
    def last_activity
        Event.select(:date, :interaction_type).where(contact_id: self.id)
        .where(interaction_type: ["group_encounter", "solo_encounter"])
        .last
    end
    
    def last_contact
        Event.select(:date, :interaction_type).where(contact_id: self.id)
        .where.not(interaction_type: ["group_encounter", "solo_encounter"])
        .last
    end
    
    def upcoming_events
        Event.where('contact_id = ? AND date >= ?', self.id, Date.today).order('date DESC').limit(3)
    end

    def recent_events
        Event.where('contact_id = ? AND date < ?', self.id, Date.today).order('date ASC').limit(3)
    end

    def display_contact_image
        if contact_image.key
            self.contact_image.key
        else
            "default_ilnk3n.jpg"
        end
    end

    def display_birthday
        if birthday
            birthday.strftime("%m/%d/%y")
        else
            false
        end
    end

    def set_nils
        self.address = nil if self.address.blank?
        self.phone_number = nil if self.phone_number.blank?
        self.email = nil if self.email.blank?
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    before_action :require_ownership, except: [:index, :new, :create]

    def index
        @contacts = Contact.includes(contact_image_attachment: :blob).where(user_id: current_user.id).order('first_name')
    end

    def show
        @contact = Contact.find(params[:id])

        @last_activity = @contact.last_activity
        @last_contact = @contact.last_contact

        @upcoming_events = @contact.upcoming_events
        @recent_events = @contact.recent_events
    end

    def new
        @contact = current_user.contacts.new
    end

    def create
        @contact = current_user.contacts.new(contact_params)
        if @contact.save
            flash[:success] = "#{@contact.first_name} was succesfully saved!"
            redirect_to contacts_url
        else
            flash.now[:error] = @contact.errors.full_messages
            render :new
        end
    end

    def edit
        @contact = Contact.find(params[:id])
    end

    def update
        @contact = Contact.find(params[:id])
        if @contact.update(contact_params)
            flash[:success] = "Contact updated!"
            redirect_to @contact
        else
            flash.now[:error] = @contact.errors.full_messages
            render :edit
        end
    end

    def destroy
        @contact = Contact.find(params[:id])
        if @contact.destroy
            flash[:success] = 'Contact successfully deleted'
            redirect_to contacts_url
        else
            flash[:error] = @contact.errors.full_messages
            redirect_back(fallback_location: contacts_url)
        end
    end

    private

        def contact_params
            params.require(:contact).permit(:user_id, :first_name, :last_name, :contact_image, :nickname, :birthday, :address, :email, :phone_number)
        end

        def require_ownership
            contact = Contact.find(params[:id])
            unless contact.user_id == current_user.id
                response = {error: "You don't own that contact"}
                render json: response, status: 401
            end
        end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact_form.html.erb
<div class="columns">
    <div class="column is-one-quarter">
        <%= simple_form_for contact, defaults: {input_html: {class: "input"}} do |f| %>
            <%= f.input :first_name %>
            <%= f.input :last_name %>
<%#             
            <div id="js-file" class="file has-name">
                <label class="file-label">
                    <input class="file-input" type="file" name="contact[contact_image]">
                    <span class="file-cta">
                    <span class="file-label">
                        Choose a file…
                    </span>
                    </span>
                    <span class="file-name">
                    No file selected
                    </span>
                </label>
            </div> 
%>

            <%= f.input :contact_image, direct_upload: true %>
            <%= f.input :nickname %>
            <%= f.input :birthday, as: :date, html5: true, start_year: Date.today.year - 90, end_year: Date.today.year, order: [:month, :day, :year] %>
            <%= f.input :address %>
            <%= f.input :email %>
            <%= f.input :phone_number, as: :tel %>
            <%= f.button :submit %>
            <%= link_to "Cancel", :back, class: "button is-light" %>
        <% end %>
    
    </div>
</div>

<%# <script>
  const fileInput = document.querySelector('#js-file input[type=file]');
  fileInput.onchange = () => {
    if (fileInput.files.length > 0) {
      const fileName = document.querySelector('#js-file .file-name');
      fileName.textContent = fileInput.files[0].name;
    }
  }
</script> %>

app/views/contacts/edit.html.erb
<h1 class="title is-1">Edit <%= "#{@contact.first_name}'s information" %></h1>

<%= render partial:'contact_form', locals: {contact: @contact} %>

app/views/contacts/index.html.erb
<div class="contact-index">
<h1 class="title is-1">Contacts</h1>
<div class="columns is-multiline">
        <% @contacts.each do |contact| %>
        <div class="column is-one-third">
            <div class="box">
            <article class="media">
                <div class="media-left">
                    <figure class="image is-64x64">
                        <%= cl_image_tag(contact.display_contact_image, quality: 80, gravity: 'faces', height: 80, width: 80, fetch_format: :auto, crop: 'fill', class: 'is-rounded') %>
                        <%# Not sure if gravity counts as a transformation for the default image. If so, will need to alter function to include gravity or not %>
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <%= link_to contact.first_name, contact_path(contact), class: "contact-index-name" %>
                            <br>
                            🎂<%= contact.birthday.strftime("%m/%d/%y") if contact.birthday %>
                            <br>
                            <%= link_to "📅 New event", new_contact_event_path(contact), class: 'button is-small is-primary is-light is-outlined' %>
                            <%#= link_to "✏️ Edit contact", edit_contact_path(contact), class: 'button is-small is-light' %>
                            <%#= link_to "🗑️ Delete Contact", contact_path(contact), method: :delete, data: {confirm: "Are you sure?"}, class: "button is-danger is-small is-light" %>
                        </p>
                    </div>
                </div>
            </article>
        </div>
        </div>
        <% end %>
</div>
        <br>
        <%= link_to "New contact", new_contact_path, class: "button is-primary" %>

</div>

app/views/contacts/new.html.erb
<h1 class="title is-1">New Contact</h1>

<%= render partial: 'contact_form', locals: {contact: @contact} %>

app/views/contacts/show.html.erb
<section class="section">
<figure class="image is-128x128">
    <%= cl_image_tag(@contact.display_contact_image, quality: 80, gravity: 'faces', height: 150, width: 150, fetch_format: :auto, crop: 'fill', class: 'is-rounded') %>
    <%# Not sure if gravity counts as a transformation for the default image. If so, will need to alter function to include gravity or not %>
</figure>

<div class="block">
    <h1 class="title is-1"><%= @contact.full_name %></h1>
    <p>🎂 <%= @contact.display_birthday || "No birthday saved!" %></p>
    <div class="block">
        <%= link_to "✏️ Edit contact", edit_contact_path(@contact), class: 'button is-small is-light' %> 
        <%= link_to "🗑️ Delete contact", contact_path(@contact), class: 'button is-danger is-small', method: :delete, data: {confirm: "Are you sure?"} %>
    <div>
</div>
<aside class="block">
    <address>
        🏠 <%= @contact.address || 'No address saved!' %>
        <br>
        📧 <%= @contact.email || 'No email saved!' %>
        <br>
        ☎️ <%= @contact.phone_number || 'No phone number saved!' %>
    </address>
</aside>

<p class="block">
    <% if @last_contact %>
        <%= "last contact was a #{@last_contact.interaction_type} on #{@last_contact.date.strftime("%m/%d/%y")} " %>
    <% else %>
        You haven't contacted this person yet! 
    <% end %>
    |
    <% if @last_activity %>
        <%= " Last in person activity was a #{@last_activity.interaction_type} on #{@last_activity.date.strftime("%m/%d/%y")}"%>
    <% else %>
        You haven't done any activities with this person yet!
    <% end %>
</p>

<div class="block">
    <%= link_to "New event", new_contact_event_path(@contact), class: 'button is-primary' %>
</div>

</section>


<section class="section">
    <h3 class="title is-3">
        Upcoming Events:
    </h3>
    <div class="columns">
        <div class="column is-half">

            <% if !@upcoming_events.empty? %>
                <% @upcoming_events.each do |e| %>
                    <div class="box contact-show-events">
                        <%= e.interaction_type %> on <%= e.date.strftime("%m/%d/%y") %>

                        <%= link_to "Edit Event", edit_event_path(e), class: 'button is-small is-light event-show-cancel' %>
                        <%= link_to "Cancel Event", event_path(e), 
                            class: 'button is-small is-danger is-light event-show-cancel', 
                            method: :delete, 
                            data: {confirm: "Are you sure?"}
                        %>
                    </div>
                <% end %>
            <% else %>
                No upcoming events with this friend! Maybe you should plan one?
            <% end %>
        </div>
    </div>
</section>

<section class="section">
    <h3 class="title is-3">
        Recent Events:
    </h3>
    <div class="columns">
        <div class="column is-half">
            <% if !@recent_events.empty? %>
                <% @recent_events.each do |e| %>
                    <div class="box">
                        <%= e.date.strftime("%m/%d/%y")%>: <%= e.interaction_type %>
                        <%= link_to "✏️", edit_event_path(e), class: 'button is-small is-light event-show-cancel' %>
                        <%= link_to "🗑️", event_path(e), 
                            class: 'button is-small is-danger is-light event-show-cancel', 
                            method: :delete, 
                            data: {confirm: "Are you sure?"}
                        %>
                    </div>
                <% end %>
            <% else %>
                No recent events with this friend. Get out there ad start making memories!
            <% end %>
        </div>
    </div>
    <%# will need to use react or something to make the description pop up on click/hover.
    Need to decide if there should be a way to view ALL past events %>
</section>